name: build-and-deploy-web

on:
    push:
        branches: ["main"]
        paths:
            - "apps/web/**"
            - ".github/workflows/web.yml"

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: yarn
                  cache-dependency-path: apps/web/yarn.lock

            - name: Install dependencies
              working-directory: apps/web
              run: yarn install --frozen-lockfile

            - name: Build Astro
              working-directory: apps/web
              run: yarn build
              # gera apps/web/dist

            - name: Configure AWS (Magalu Object Storage)
              uses: aws-actions/configure-aws-credentials@v4
              with:
                  aws-access-key-id: ${{ secrets.MAGALU_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.MAGALU_SECRET_ACCESS_KEY }}
                  aws-region: us-east-1 # não é usado, mas o action exige

            - name: Deploy to Magalu Object Storage
              working-directory: apps/web
              run: |
                  aws \
                    --endpoint-url https://br-se1.magaluobjects.com \
                    s3 sync dist/ s3://astro-web-prod/ \
                    --delete
