name: build-and-deploy-web

on:
    push:
        branches: ["main"]
        paths:
            - "apps/web/**"
            - ".github/workflows/web.yml"

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  # enquanto você não tiver yarn.lock, NÃO usa cache:yarn
                  cache: yarn
                  cache-dependency-path: apps/web/yarn.lock

            - name: Install dependencies
              working-directory: apps/web
              run: yarn install

            - name: Build Astro
              working-directory: apps/web
              run: yarn build

            - name: Check AWS CLI
              run: aws --version

            - name: Deploy to Magalu Object Storage
              working-directory: apps/web
              env:
                  AWS_ACCESS_KEY_ID: ${{ secrets.MAGALU_ACCESS_KEY }}
                  AWS_SECRET_ACCESS_KEY: ${{ secrets.MAGALU_SECRET_KEY }}
                  AWS_DEFAULT_REGION: us-east-1
                  AWS_EC2_METADATA_DISABLED: "true"
              run: |
                  aws \
                    --endpoint-url https://br-se1.magaluobjects.com \
                    s3 sync dist/ s3://astro-web-prod/ \
                    --delete
